swagger: "2.0"
info:
  version: "0.0.1"
  title: "Minimal Express boilerplate"
  description: "This is a minimal express boilerplate that includes moongoose, swagger documentation, dotenv variables and integration tests"
  contact: "adrianvlupu@gmail.com"
basePath: "localhost:3000/"
tags:
- name: "ping"
  description: "endpoint for testing things out"
schemes:
- "http"
paths:
  /ping/hello:
    get:
      tags:
      - "ping"
      summary: "check if the API is online"
      description: "returns a hello message with the processid"
      responses:
        200:
          description: "OK"
  /ping/db:
    get:
      tags: 
      - "ping"
      summary: "hits the database"
      produces:
      - "application/json"
      responses:
        201:
          description: "OK"
  /ping/error:
    get:
      tags:
      - "ping"
      summary: "returns a sample error"
      responses:
        500:
          description: "Internal Server Error"
        